@php
$site = ['support_whatsapp' => '00972569177111', 'email' => 'قيد التحديث', 'support_hours' => 'يتم الرد خلال يوم عمل واحد، من السبت إلى الخميس.'];
$whatsapp = preg_replace('/\D+/', '', $site['support_whatsapp']);
@endphp
<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>تواصل معنا | مدرسة طموح الإلكترونية</title><link href="https://fonts.googleapis.com/css2?family=Baloo+Bhaijaan+2:wght@400;700;800&family=Tajawal:wght@400;500;700;800&display=swap" rel="stylesheet"><style>:root{--p:#2e1a47;--c:#ff6b4a;--m:#22a66b;--s:#ffc857;--ink:#241432;--muted:#736686;--line:#efe3f1;--paper:#fffdfa}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Tajawal,sans-serif}.container,.wrap{max-width:1160px;margin:auto;padding-right:24px;padding-left:24px}a{text-decoration:none}.topbar{background:var(--paper);position:sticky;top:0;z-index:30;padding:14px 0}.nav{display:flex;align-items:center;justify-content:space-between;background:#fff;border:1px solid var(--line);border-radius:99px;padding:8px 10px 8px 22px;box-shadow:0 10px 30px -22px #2e1a4740}.brand{display:flex;align-items:center;gap:10px;color:var(--ink)}.brand-mark{width:40px;height:40px;border-radius:14px 14px 14px 4px;background:var(--c);color:#fff;display:grid;place-items:center;font:19px 'Baloo Bhaijaan 2';transform:rotate(-3deg)}.brand b{font:700 17px 'Baloo Bhaijaan 2'}.brand small{display:block;font-size:10px;color:var(--muted)}.nav nav{display:flex;gap:26px}.nav nav a{color:var(--ink);font-size:13px;font-weight:500}.nav nav .active,.nav nav a:hover{color:#e14f2e}.actions{display:flex;gap:10px;align-items:center}.ghost{color:var(--ink);font-size:13px;font-weight:600;padding:10px 8px}.primary{background:var(--c);color:#fff;border-radius:99px;padding:12px 22px;font-size:13px;font-weight:700}.wrap{max-width:850px;padding-top:45px;padding-bottom:70px}.hero{background:var(--p);color:#fff;border-radius:32px 32px 8px 32px;padding:38px;position:relative;overflow:hidden}.hero:after{content:'';position:absolute;width:180px;height:180px;left:-55px;top:-65px;border-radius:50%;background:var(--s);opacity:.15}.hero h1{font:800 36px 'Baloo Bhaijaan 2';margin:0 0 8px;position:relative;z-index:1}.hero p{color:#d9cbe8;line-height:2;margin:0;position:relative;z-index:1}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:18px}.card{border:1px solid var(--line);background:#fff;border-radius:24px 24px 24px 6px;padding:24px}.card h2{font:700 22px 'Baloo Bhaijaan 2';margin:0 0 12px}.card p{font-size:14px;line-height:2;color:var(--muted)}.channel{display:block;text-decoration:none;color:#fff;padding:13px 16px;border-radius:12px;font-weight:800;margin-top:10px;text-align:center}.whatsapp{background:#25D366}.email{color:#e14f2e;font-weight:800;word-break:break-word}.note{background:#fff8e8;border-color:#ffe6a2}@media(max-width:650px){.nav nav,.ghost{display:none}.wrap{padding-top:30px}.grid{grid-template-columns:1fr}.hero h1{font-size:30px}}</style><style>
.topbar{position:sticky;top:0;z-index:50;background:#fffdfaf2;backdrop-filter:blur(12px);border-bottom:1px solid #ebdfeb}.nav{min-height:76px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{display:flex;align-items:center;gap:12px;font-size:20px;font-weight:800}.brand img{width:48px;height:48px;border-radius:14px;object-fit:cover}.brand small{display:block;color:#71647d;font-size:10px;font-weight:500;margin-top:-3px}.links{display:flex;align-items:center;gap:26px}.links a{font-size:13px;font-weight:700;color:#594b64}.links a:hover,.links a.active{color:#f4674a}.actions{display:flex;gap:9px;align-items:center}.button{display:inline-block;border:0;border-radius:99px;padding:11px 19px;background:#f4674a;color:#fff;font:700 13px Cairo;cursor:pointer;transition:.2s}.button:hover{transform:translateY(-2px);background:#df4e33}.button.ghost{background:transparent;color:#241432}.menu-button{display:none;width:43px;height:43px;place-items:center;border:0;border-radius:12px;background:#21133d;color:#fff;font-size:24px;cursor:pointer}@media(max-width:760px){.nav{min-height:68px}.brand{font-size:16px}.links{display:none;position:absolute;top:68px;right:18px;left:18px;padding:10px;background:#fff;border:1px solid #ebdfeb;border-radius:18px;box-shadow:0 20px 35px #21133d24}.links.open{display:grid;gap:3px}.links a{padding:10px 12px;border-radius:9px}.links a:hover{background:#fff0e9}.actions{display:none}.menu-button{display:grid}}
</style></head><body>@include('partials.site-nav')<main class="wrap"><section class="hero"><h1>تواصل معنا</h1><p>فريق الدعم جاهز لمساعدتك في التسجيل، الدفع، الدخول للحصص، أو أي استفسار يتعلق بالمنصة.</p></section><section class="grid"><article class="card"><h2>تواصل سريع</h2><a class="channel whatsapp" target="_blank" rel="noopener" href="https://wa.me/<?=$whatsapp?>">تواصل عبر واتساب</a><p>رقم الدعم: <?=htmlspecialchars($site['support_whatsapp'])?></p></article><article class="card"><h2>البريد الإلكتروني</h2><p>يمكنك مراسلتنا على:</p><p class="email"><?=htmlspecialchars($site['email'])?></p><h2 style="margin-top:24px">وقت الرد المتوقع</h2><p><?=htmlspecialchars($site['support_hours'])?></p></article><article class="card note"><h2>ملاحظة مهمة</h2><p>للحصول على رد أسرع، اذكر اسم الطالب ورقم الجوال والمادة التي تحتاج مساعدة بشأنها.</p></article></section></main></body></html>





