@extends('layouts.admin', ['title' => 'طلبات المدرسين'])

@section('content')
<style>
    .applications-head{display:flex;justify-content:space-between;align-items:end;gap:18px;margin-bottom:24px}.applications-head h1{margin:0}.applications-head p{margin:5px 0 0}.applications-count{padding:9px 13px;border-radius:99px;background:#fff0eb;color:#d84e31;font-size:11px;font-weight:800}.applications-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.application-card{position:relative;overflow:hidden;padding:21px;background:#fff;border:1px solid var(--line);border-radius:22px}.application-card:before{content:'';position:absolute;inset:0 0 auto;height:5px;background:linear-gradient(90deg,#ff6b4a,#ffc857)}.application-top{display:flex;align-items:center;gap:12px;margin-bottom:16px}.application-avatar{width:58px;height:58px;display:grid;place-items:center;flex:0 0 58px;border-radius:18px;background:linear-gradient(135deg,#efe5ff,#fff0e9);color:var(--p);font-size:22px;font-weight:800}.application-card h2{margin:0 0 4px;font-size:17px}.application-card .specialization{margin:0;color:var(--muted);font-size:12px}.application-meta{display:grid;gap:8px;padding:13px;margin-bottom:15px;background:#fffafc;border-radius:13px;color:var(--muted);font-size:11px}.application-preview{min-height:43px;margin:0 0 16px;color:var(--muted);font-size:12px;line-height:1.8}.application-date{display:block;margin-bottom:12px;color:#9a8ca4;font-size:10px}.details-button{width:100%;border:0;border-radius:11px;padding:11px;background:var(--p);color:#fff;font:800 12px Tajawal;cursor:pointer}.details-button:hover{background:#51337b}.application-modal{position:fixed;inset:0;z-index:100;display:none;place-items:center;padding:18px;background:rgba(36,20,50,.48)}.application-modal.open{display:grid}.application-dialog{width:min(620px,100%);max-height:calc(100vh - 36px);overflow:auto;padding:25px;background:#fff;border-radius:22px;box-shadow:0 24px 70px rgba(36,20,50,.25)}.dialog-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:20px}.dialog-head h2{margin:0}.close-dialog{width:34px;height:34px;border:0;border-radius:10px;background:#fff0eb;color:#c7462d;font-size:20px;cursor:pointer}.details-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.detail-item{padding:13px;background:#fffafc;border:1px solid var(--line);border-radius:12px}.detail-item.wide{grid-column:1/-1}.detail-item strong{display:block;margin-bottom:5px;color:var(--muted);font-size:11px}.detail-item span,.detail-item p{margin:0;color:var(--ink);font-size:13px;line-height:1.8;white-space:pre-line}@media(max-width:1050px){.applications-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.applications-head{display:block}.applications-count{display:inline-block;margin-top:12px}.applications-grid{grid-template-columns:1fr}.details-grid{grid-template-columns:1fr}.detail-item.wide{grid-column:auto}}
</style>

<header class="applications-head"><div><h1>طلبات انضمام المدرسين</h1><p class="muted">راجع بيانات المتقدمين وافتح تفاصيل أي طلب من البطاقة.</p></div><span class="applications-count">{{ $applications->count() }} طلب</span></header>

<div class="applications-grid">
    @forelse($applications as $application)
        <article class="application-card">
            <div class="application-top"><div class="application-avatar">{{ mb_substr($application->full_name ?? 'م', 0, 1) }}</div><div><h2>{{ $application->full_name ?? 'بدون اسم' }}</h2><p class="specialization">{{ $application->specialization ?: 'تخصص غير محدد' }}</p></div></div>
            <div class="application-meta"><span>☎ {{ $application->phone ?: 'لا يوجد هاتف' }}</span><span>✉ {{ $application->email ?: 'لا يوجد بريد' }}</span></div>
            <p class="application-preview">{{ $application->qualifications ?: 'لا توجد مؤهلات مضافة.' }}</p>
            <small class="application-date">{{ $application->created_at ?: 'بدون تاريخ' }}</small>
            <button class="details-button" type="button" data-application-id="{{ $application->id }}">عرض التفاصيل</button>
            @if(($application->status ?? 'pending') === 'pending')
                <div style="display:flex;gap:7px;margin-top:8px"><form method="post" action="{{ route('admin.applications.approve', $application->id) }}" style="flex:1">@csrf<button class="details-button" style="background:#22a66b" type="submit">قبول وإنشاء الحساب</button></form><form method="post" action="{{ route('admin.applications.reject', $application->id) }}">@csrf<button class="details-button" style="background:#fff1f2;color:#b91c1c" type="submit">رفض</button></form></div>
            @endif
        </article>
    @empty
        <p class="muted">لا توجد طلبات.</p>
    @endforelse
</div>

<div class="application-modal" id="application-modal" role="dialog" aria-modal="true" aria-labelledby="application-dialog-title"><div class="application-dialog"><div class="dialog-head"><h2 id="application-dialog-title">تفاصيل طلب المدرس</h2><button class="close-dialog" type="button" aria-label="إغلاق">×</button></div><div class="details-grid" id="application-details"></div></div></div>

<script>
document.addEventListener('DOMContentLoaded',function(){const modal=document.querySelector('#application-modal'),details=document.querySelector('#application-details'),applications=@json($applications->keyBy('id')),labels={full_name:'الاسم الكامل',phone:'رقم الهاتف',email:'البريد الإلكتروني',specialization:'التخصص',qualifications:'المؤهلات',years_experience:'سنوات الخبرة',bio:'النبذة التعريفية',verification_source:'مصدر التحقق',status:'الحالة',created_at:'تاريخ التقديم'};function closeModal(){modal.classList.remove('open')}document.querySelectorAll('.details-button').forEach(function(button){button.addEventListener('click',function(){const application=applications[button.dataset.applicationId];details.innerHTML='';Object.keys(labels).forEach(function(key){const item=document.createElement('div');item.className='detail-item'+(['qualifications','bio','verification_source'].includes(key)?' wide':'');const title=document.createElement('strong');title.textContent=labels[key];const content=document.createElement('p');const value=application[key];content.textContent=value===null||value===undefined||value===''?'غير متوفر':value;item.append(title,content);details.appendChild(item)});modal.classList.add('open')})});modal.querySelector('.close-dialog').addEventListener('click',closeModal);modal.addEventListener('click',function(event){if(event.target===modal)closeModal()});document.addEventListener('keydown',function(event){if(event.key==='Escape')closeModal()})});
</script>
@endsection
