<?php

return [
    'term_label' => 'الفصل الدراسي',
    'whatsapp' => [
        'palestine' => '00972595124090',
        'egypt' => '00201028599108',
    ],
    'regions' => [
        'palestine' => [
            'title' => 'غزة والضفة',
            'currency' => 'شيكل',
            'packages' => [
                [
                    'key' => 'grade-7',
                    'grade_level' => '7',
                    'branch' => 'general',
                    'title' => 'بكج الصف السابع',
                    'price' => 250,
                    'description' => 'تسجيل كامل مواد الصف السابع للدوام النظامي.',
                ],
                [
                    'key' => 'grade-8',
                    'grade_level' => '8',
                    'branch' => 'general',
                    'title' => 'بكج الصف الثامن',
                    'price' => 250,
                    'description' => 'تسجيل كامل مواد الصف الثامن للدوام النظامي.',
                ],
                [
                    'key' => 'grade-9',
                    'grade_level' => '9',
                    'branch' => 'general',
                    'title' => 'بكج الصف التاسع',
                    'price' => 250,
                    'description' => 'تسجيل كامل مواد الصف التاسع للدوام النظامي.',
                ],
                [
                    'key' => 'grade-10',
                    'grade_level' => '10',
                    'branch' => 'general',
                    'title' => 'بكج الصف العاشر',
                    'price' => 300,
                    'description' => 'تسجيل كامل مواد الصف العاشر للدوام النظامي.',
                ],
                [
                    'key' => 'grade-11-scientific',
                    'grade_level' => '11',
                    'branch' => 'scientific',
                    'title' => 'بكج الصف 11 العلمي',
                    'price' => 380,
                    'description' => 'تسجيل كامل مواد الصف 11 العلمي للدوام النظامي.',
                ],
                [
                    'key' => 'grade-11-literary',
                    'grade_level' => '11',
                    'branch' => 'literary',
                    'title' => 'بكج الصف 11 الأدبي',
                    'price' => 350,
                    'description' => 'تسجيل كامل مواد الصف 11 الأدبي للدوام النظامي.',
                ],
                [
                    'key' => 'grade-12-scientific',
                    'grade_level' => '12',
                    'branch' => 'scientific',
                    'title' => 'بكج الصف 12 العلمي',
                    'price' => 500,
                    'description' => 'تسجيل كامل مواد الصف 12 العلمي للدوام النظامي.',
                ],
                [
                    'key' => 'grade-12-literary',
                    'grade_level' => '12',
                    'branch' => 'literary',
                    'title' => 'بكج الصف 12 الأدبي',
                    'price' => 450,
                    'description' => 'تسجيل كامل مواد الصف 12 الأدبي للدوام النظامي.',
                ],
            ],
        ],
        'egypt' => [
            'title' => 'مصر',
            'currency' => 'جنيه مصري',
            'packages' => [
                [
                    'key' => 'grade-7',
                    'grade_level' => '7',
                    'branch' => 'general',
                    'title' => 'بكج الصف السابع',
                    'price' => 4000,
                    'description' => 'تسجيل كامل مواد الصف السابع للدوام النظامي.',
                ],
                [
                    'key' => 'grade-8',
                    'grade_level' => '8',
                    'branch' => 'general',
                    'title' => 'بكج الصف الثامن',
                    'price' => 4000,
                    'description' => 'تسجيل كامل مواد الصف الثامن للدوام النظامي.',
                ],
                [
                    'key' => 'grade-9',
                    'grade_level' => '9',
                    'branch' => 'general',
                    'title' => 'بكج الصف التاسع',
                    'price' => 4000,
                    'description' => 'تسجيل كامل مواد الصف التاسع للدوام النظامي.',
                ],
                [
                    'key' => 'grade-10',
                    'grade_level' => '10',
                    'branch' => 'general',
                    'title' => 'بكج الصف العاشر',
                    'price' => 5000,
                    'description' => 'تسجيل كامل مواد الصف العاشر للدوام النظامي.',
                ],
                [
                    'key' => 'grade-11-scientific',
                    'grade_level' => '11',
                    'branch' => 'scientific',
                    'title' => 'بكج الصف 11 العلمي',
                    'price' => 6400,
                    'description' => 'تسجيل كامل مواد الصف 11 العلمي للدوام النظامي.',
                ],
                [
                    'key' => 'grade-11-literary',
                    'grade_level' => '11',
                    'branch' => 'literary',
                    'title' => 'بكج الصف 11 الأدبي',
                    'price' => 6000,
                    'description' => 'تسجيل كامل مواد الصف 11 الأدبي للدوام النظامي.',
                ],
                [
                    'key' => 'grade-12-scientific',
                    'grade_level' => '12',
                    'branch' => 'scientific',
                    'title' => 'بكج التوجيهي العلمي',
                    'price' => 8400,
                    'description' => 'تسجيل كامل مواد التوجيهي العلمي للدوام النظامي.',
                ],
                [
                    'key' => 'grade-12-literary',
                    'grade_level' => '12',
                    'branch' => 'literary',
                    'title' => 'بكج التوجيهي الأدبي',
                    'price' => 7500,
                    'description' => 'تسجيل كامل مواد التوجيهي الأدبي للدوام النظامي.',
                ],
            ],
        ],
    ],
    'packages' => [
    ],
];
